### ISSUE TITLE
how much is the φ of EfficientNet-B7 ？

### ISSUE THREAD

**Issue by andeyeluguo** [lukemelas/EfficientNet-PyTorch#1]
The paper seems not show the value φ of EfficientNet-B7

**Comment by yoookoo** [comment]
> The paper seems not show the value φ of EfficientNet-B7
7......

**Comment by belskikh** [comment]
There are values of alpha, betta and gamma in code
https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_builder.py#L28
