### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by btoob** [lukemelas/EfficientNet-PyTorch#103]
I'm foolish. I cannot write the one-key train code.
I hate myself.
so could u update the code to train from scratch ?

**Comment by llwowowowoll** [comment]
+1

**Comment by michaelklachko** [comment]
+1

**Comment by nizhib** [comment]
It wasn't trained neither with a one key, nor with a thousand keys — the repo uses the weights ported from original tensorflow code and the pytorch models they fit.

If you are brave enough, you can look at "official" pytorch imagenet one-key training script — https://github.com/pytorch/examples/blob/master/imagenet/main.py. They say nobody succeeds with tensorflow-first models like this one though (and e.g. Inception).

And stop +1ing guys, there are reactions for that.

**Comment by michaelklachko** [comment]
What does it mean "trained with one key"? Has anyone successfully reproduced B4 or larger results on GPUs? I mean from scratch. If so, what are the h-params and number of epochs?
