### ISSUE TITLE
Using EfficientNet training Person-reid

### ISSUE THREAD

**Issue by ivylinden** [lukemelas/EfficientNet-PyTorch#11]
Hi,I used EfficientNet  to train Person reid on dataset Market1501, but the mAP is only 70+,I don't know why. Does  EfficientNet  not  suitable for feature extraction?

**Comment by lukemelas** [comment]
EfficientNet should be well suited for feature extraction as well as classification (e.g. Figure 7 in the paper). It's difficult to diagnose your issue without more information -- if you would like, you can post more information (or a full repo with code) and I'll try to look at it when I have a bit of time.

**Comment by lukemelas** [comment]
Closing this repo, feel free to re-open if there are additional questions.
