### ISSUE TITLE
Is it possible to use it as a encoder of a segmentation network?

### ISSUE THREAD

**Issue by ysssgdhr** [lukemelas/EfficientNet-PyTorch#110]
Other people have implemented EfficientNet-b4 using unet++ as its backbone to do segmentation task.
So I wonder whether this pytorch version is able to do the same or not, since it would need the features map extracted from several pervious layers.

**Comment by nizhib** [comment]
Check https://github.com/qubvel/segmentation_models.pytorch#encoders

**Comment by ysssgdhr** [comment]
Thank you very much. I'm a newbie with the pytorch. I just knew there was such a good repository.
