### ISSUE TITLE
integrating inside pytorch-vision

### ISSUE THREAD

**Issue by Borda** [lukemelas/EfficientNet-PyTorch#114]
hello, very nice work; I was wondering if you considered integrating EfficientNet also inside `pytorchvision` package... in my opinion, it would be a great addition!

**Comment by Borda** [comment]
Also, there is and follow-up work on detection as EfficientDet https://twitter.com/quocleix/status/1197682880173920256?s=20

**Comment by nizhib** [comment]
If you mean `torchvision` library than it is not an option unless the weights are reproduced with `examples/imagenet/main.py` script from scratch. No converted weights are allowed there.

**Comment by Borda** [comment]
hmmm and what about just adding the model/net/arch which can be trained individually on any standard or custom dataset?

**Comment by nizhib** [comment]
`torchvision.models` is basically a set of pretrained most common classification networks (with segmentation and detection models added only recently) trained from scratch.

EfficientNet is:
1) Relatively new model, e.g. there is still no se-resnext's (ImageNet Top-1 dated 2017);
2) Hard to be reproduced with decent performance as every tensorflow-first architectures like Inception (there is none of it in the torchvision either, though it is dated as far as 2015).

If you can create more native implementation and achieve the paper scores with pytorch imagenet trainer script, godspeed to you.
