### ISSUE TITLE
use  jupyter notebook run the "Example: Classification" ,run error 

### ISSUE THREAD

**Issue by cnxqscn** [lukemelas/EfficientNet-PyTorch#116]
-------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-7ac1d1b28dea> in <module>()
      4 with torch.no_grad():
      5     logits = model(img)
----> 6 preds = torch.topk(logits, k=5).indices.squeeze(0).tolist()
      7 
      8 print('-----')

AttributeError: 'tuple' object has no attribute 'indices'

**Comment by lukemelas** [comment]
What's your Pytorch version?

**Comment by xisi789** [comment]
> What's your Pytorch version?

same question. pytorch 0.4.1

**Comment by lukemelas** [comment]
For anyone that encounters this issue in the future, this occurs if you have an old version of PyTorch.
