### ISSUE TITLE
Resume Training

### ISSUE THREAD

**Issue by etetteh** [lukemelas/EfficientNet-PyTorch#120]
I have downloaded the model checkpoints.
Please, how do I resume training by loading the model state dict in the form
I am asking tis, because I don't know the keys used for the model_state_dict

PATH = './checkpoint/ckpt.pth'
assert os.path.isdir('checkpoint'), 'Error: no checkpoint directory found!'
checkpoint = torch.load(PATH)

model.module.load_state_dict(checkpoint['model_state_dict'], strict=True)
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
best_loss = checkpoint['loss']
best_top1 = checkpoint['top1']

**Comment by lchunleo** [comment]
hi 

i encounter this issue when i do a resume training on a checkpoint which i stopped halfway.  Any advice?
  File "train.py", line 125, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 202, in main_worker
    args.start_epoch = checkpoint['epoch']
TypeError: 'EfficientNet' object is not subscriptable


What does it meant it is "not subscriptable"?
