### ISSUE TITLE
About the residual skip connection 

### ISSUE THREAD

**Issue by ysssgdhr** [lukemelas/EfficientNet-PyTorch#124]
I wonder why there is skip connection only when the stride equals to one . Is it the origin realization of Efficient, would you please explain it ? That would be so much appreciated :) . 
@lukemelas 
![image](https://user-images.githubusercontent.com/24486813/71504422-5300b100-28b4-11ea-8f68-064e8ee76691.png)

code in MBConvBlock:

```
        # Skip connection and drop connect
        input_filters, output_filters = self._block_args.input_filters, self._block_args.output_filters
        if self.id_skip and self._block_args.stride == 1 and input_filters == output_filters:
            if drop_connect_rate:
                x = drop_connect(x, p=drop_connect_rate, training=self.training)
            x = x + inputs  # skip connection
```

What I'm saying is  , why not add residual connection to every block we have ?

**Comment by lukemelas** [comment]
Yup, I just followed the network structure described in the paper. I agree it's not completely intuitive. 

Closing this, re-open it if you have any more questions.
