### ISSUE TITLE
use jupyter notebook run the "Example: Export to ONNX " ,run error 

### ISSUE THREAD

**Issue by Johnson-yue** [lukemelas/EfficientNet-PyTorch#126]
Hi , I want to test how to export ONNX model , and I use your colab jupyter notebook  demo.
`Successfully installed efficientnet-pytorch-0.5.1`
`Successfully installed onnx-1.6.0`
and It stop in `return (%880)` , I can not see any error information. So Can you check this [colab notebook](https://colab.research.google.com/drive/1rOAEXeXHaA8uo3aG2YcFDHItlRJMV0VP)? 

b.t.w I tried using 

> model.set_swish(memory_efficient=False)

like this 
![Screenshot from 2019-12-27 17-44-44](https://user-images.githubusercontent.com/10268274/71512440-26a75d80-28d1-11ea-9360-92049f7b9ae4.png)

Even it sucessful export onnx model. But when I run `Test Export` ,that next Cell.

The system crashed!!

Hope you can check it ,thank you very much

**Comment by royinx** [comment]
Checkout #91  , it works for me on B1 & B7
```
model.set_swish(memory_efficient=False)
model.eval()
```
My Env : `efficientnet_pytorch - 0.5.1 , Pytorch - 1.5, torchvision 0.6.0, onnx - 1.6.0`

**Comment by apurvg14** [comment]
Put the model.set_swish(memory_efficient=False) line before model.eval()

**Comment by apurvg14** [comment]
Put the model.set_swish(memory_efficient=False) line before model.eval(). Working for me.

**Comment by Johnson-yue** [comment]
@apurvg14  Thank you I will try it
