### ISSUE TITLE
two  " def from_pretrained "  function ?

### ISSUE THREAD

**Issue by alicera** [lukemelas/EfficientNet-PyTorch#128]
in the efficientnet_pytorch/model.py , it has two function " from_pretrained  "
  what is the different?

def from_pretrained(cls, model_name, num_classes=1000, in_channels = 3):

def from_pretrained(cls, model_name, num_classes=1000):

**Comment by lukemelas** [comment]
Sorry about that! That's an error introduced in the last merge. I'll fix it in the next update to the repo. 

Best,
Luke

**Comment by lukemelas** [comment]
Bug squashed.
