### ISSUE TITLE
Is stride correct

### ISSUE THREAD

**Issue by liyangliu** [lukemelas/EfficientNet-PyTorch#13]
I find that in the original paper strides for 7 stages (stage 2-8 in the following table)are:
![image](https://user-images.githubusercontent.com/5159489/58864401-323df780-86e7-11e9-95e3-697d655f6b4b.png)
1, 2, 2, 1, 2, 2, 1
but in your code I find it is:
1, 2, 2, 2, 1, 2, 1
Did you do it intentionally or maybe I am wrong?

**Comment by fengfu-chris** [comment]
> I find that in the original paper strides for 7 stages (stage 2-8 in the following table)are:
> ![image](https://user-images.githubusercontent.com/5159489/58864401-323df780-86e7-11e9-95e3-697d655f6b4b.png)
> 1, 2, 2, 1, 2, 2, 1
> but in your code I find it is:
> 1, 2, 2, 2, 1, 2, 1
> Did you do it intentionally or maybe I am wrong?

Code is correct, the original paper has mistake in writing.
https://github.com/tensorflow/tpu/issues/383

**Comment by lukemelas** [comment]
Yes, the stride in the code is correct.
