### ISSUE TITLE
```from_pretrained``` function with ```in_channels``` attribute can not be called

### ISSUE THREAD

**Issue by arthurnage** [lukemelas/EfficientNet-PyTorch#131]
https://github.com/lukemelas/EfficientNet-PyTorch/blob/61066be42f1811f62a589102a3af2c3f2492c102/efficientnet_pytorch/model.py#L209

That is because function def from_pretrained(cls, model_name, num_classes=1000): at line 219 overwrites it.

**Comment by lukemelas** [comment]
Yes, thanks for the issue. This was brought up in #128. It should now be fixed. Let me know if you have any issues! :)
