### ISSUE TITLE
Why the model parameter mentioned in the paper is only 5.3m, but the downloaded model file is 21.4m

### ISSUE THREAD

**Issue by Broad-sky** [lukemelas/EfficientNet-PyTorch#132]
Why the model parameter mentioned in the paper is only 5.3m, but the downloaded model file is 21.4m？how to explain this status?

**Comment by lukemelas** [comment]
See #40 and let me know if anything is still unclear

**Comment by lukemelas** [comment]
Closing this. Re-open it if there are any issues/confusions.
