### ISSUE TITLE
Cant import url_map after update

### ISSUE THREAD

**Issue by Tramtadama** [lukemelas/EfficientNet-PyTorch#135]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-b9e13fa886e0> in <module>
----> 1 import segmentation_models_pytorch as smp

/opt/conda/lib/python3.6/site-packages/segmentation_models_pytorch/__init__.py in <module>
----> 1 from .unet import Unet
      2 from .linknet import Linknet
      3 from .fpn import FPN
      4 from .pspnet import PSPNet
      5 

/opt/conda/lib/python3.6/site-packages/segmentation_models_pytorch/unet/__init__.py in <module>
----> 1 from .model import Unet

/opt/conda/lib/python3.6/site-packages/segmentation_models_pytorch/unet/model.py in <module>
      1 from typing import Optional, Union, List
      2 from .decoder import UnetDecoder
----> 3 from ..encoders import get_encoder
      4 from ..base import SegmentationModel
      5 from ..base import SegmentationHead, ClassificationHead

/opt/conda/lib/python3.6/site-packages/segmentation_models_pytorch/encoders/__init__.py in <module>
      9 from .inceptionresnetv2 import inceptionresnetv2_encoders
     10 from .inceptionv4 import inceptionv4_encoders
---> 11 from .efficientnet import efficient_net_encoders
     12 from .mobilenet import mobilenet_encoders
     13 from .xception import xception_encoders

/opt/conda/lib/python3.6/site-packages/segmentation_models_pytorch/encoders/efficientnet.py in <module>
     25 
     26 from efficientnet_pytorch import EfficientNet
---> 27 from efficientnet_pytorch.utils import url_map, get_model_params
     28 
     29 from ._base import EncoderMixin

ImportError: cannot import name 'url_map'

**Comment by lukemelas** [comment]
I renamed the map in this update and I see that this has caused issues. I will switch it back.

**Comment by lukemelas** [comment]
Just fixed it. Let me know if everything works.

**Comment by Tramtadama** [comment]
Works fine again. Thank you. Keep up the good work!

**Comment by lukemelas** [comment]
Awesome
