### ISSUE TITLE
Use relu version?

### ISSUE THREAD

**Issue by ahundt** [lukemelas/EfficientNet-PyTorch#136]
Is there a way to go back to the relu version of the efficientnet?

On my application here is the expected behavior, higher is better:
![2020-01-23-18-39-50-densenet](https://user-images.githubusercontent.com/55744/73085037-0c46ac80-3e9c-11ea-8b74-6fcb4de85a03.png)

Here is the actual behavior I'm getting with the new swish version of efficientnet:
![2020-01-23-22-24-33-efficientnet](https://user-images.githubusercontent.com/55744/73085038-0c46ac80-3e9c-11ea-820b-ddcdaa2ab727.png)

**Comment by ahundt** [comment]
Honestly discovering this really major yet silent change to the internals has cost me a couple weeks of time, heh...

**Comment by ahundt** [comment]
Can you also add the old relu pretrained weights to be available? I don't think I have the file anymore. You mentioned hosting trouble, I believe you can simply drop the files in the "release" area of this github page, and github will host your pretrained weights for free.

**Comment by lukemelas** [comment]
Hi @ahundt,

I'm not sure what you mean by the old relu version. As shown in this commit from June, the repo has always used the swish activation (or else the pretrained weights would not work): https://github.com/lukemelas/EfficientNet-PyTorch/blob/6d36a35dfdcb65a7915472286486e1b8f750e5b6/efficientnet_pytorch/utils.py#L38

Let me know if I'm misunderstanding.

**Comment by ahundt** [comment]
my mistake, I posted this too early. I'm sorry for the noise.

**Comment by lukemelas** [comment]
No worries!
