### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden when downloading the efficientnet-b4-e116e8b3.pth

### ISSUE THREAD

**Issue by qiminchen** [lukemelas/EfficientNet-PyTorch#138]
Hi,

the error "Anonymous caller does not have storage.objects.get access to public-models/efficientnet-b4-e116e8b3.pth." appears when trying to download the pretrained efficientnet-b4.

**Comment by lukemelas** [comment]
Do the other models work for you, or just b4?

**Comment by lukemelas** [comment]
I will try to replicate tonight and get back to you

**Comment by qiminchen** [comment]
b0-b3 work fine, but not b4 and b5, haven’t tried higher version

**Comment by lukemelas** [comment]
Very strange.

**Comment by lukemelas** [comment]
Can you try going to https://publicmodels.blob.core.windows.net/container/advprop/efficientnet-b4-44fb3a87.pth in a web browser? Or running 
```
wget https://publicmodels.blob.core.windows.net/container/advprop/efficientnet-b4-44fb3a87.pth
```
Do you still get an HTTP error?

**Comment by qiminchen** [comment]
thanks, it works now

**Comment by qiminchen** [comment]
if I try to download the pretrained efficientnet-b4/b5 from [Kaggle](https://www.kaggle.com/hmendonca/efficientnet-pytorch/version/1#efficientnet-b4-e116e8b3.pth),  still not working

![image](https://user-images.githubusercontent.com/45860234/73131484-78223580-3fc0-11ea-80eb-6a4a122fc83d.png)

**Comment by lukemelas** [comment]
I'm going to close this, but re-open it if you have any more issues. Strange stuff.

**Comment by bfolkens** [comment]
Also getting this with http://storage.googleapis.com/public-models/efficientnet/efficientnet-b5-b6417697.pth

**Comment by bfolkens** [comment]
**Update** - FWIW, just found it at:

```
https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b5-b6417697.pth
```

**Comment by lukemelas** [comment]
Great. Yes, unfortunately I had to disable the Google Cloud urls because it was getting too expensive to keep hosting the pretrained models on Google Cloud.

**Comment by cristyioan2000** [comment]
Can you please update in the code the url_map dict with the new url to the .pth ? or post here the new location of the .pth files, thank you!

**Comment by bfolkens** [comment]
Hi @cristyioan2000 - I believe the URLs are up to date in the most recent version.  I had a problem with an older version I had pinned in a project.

**Comment by yuliok0715** [comment]
HI, I use the last version of your lib from pip (0.18.2) and I'm still getting 403. Could you please send actual links?

**Comment by cristyioan2000** [comment]
Hi,

The issue it's closed. Everything it's fine now.

Thank you

În mie., 22 iul. 2020 la 15:25, Yulia Honcharenko <notifications@github.com>
a scris:
