### ISSUE TITLE
speed performance of efficientnetB0 and resnet34

### ISSUE THREAD

**Issue by victorzhucompass** [lukemelas/EfficientNet-PyTorch#140]
given the #parameters:
efficientnetB0: ~5.3M
resnet34: ~22M

i am expecting speed performance of effcientnetB0:resnet34 = 4:1. However, from local test, it shows the speed performance is close to 1:1.

any thoughts?

**Comment by mukesh-mehta** [comment]
Hey,
Were you able to resolve this?? I am also facing the same issue.
