### ISSUE TITLE
feature extraction

### ISSUE THREAD

**Issue by qiminchen** [lukemelas/EfficientNet-PyTorch#141]
Hi, 

What if I want the features that have the size of [batch_size, 1280] instead of the features of the final convolution layer (size of [batch_size, 1280, 7, 7]), what should I do? Can I add
`x = nn.functional.adaptive_avg_pool2d(x, 1).squeeze(-1).squeeze(-1)`
before returning `x` in `extract_features` function? Otherwise, what would you recommend to do? Thanks in advance!

**Comment by lukemelas** [comment]
Yup, you got it!
