### ISSUE TITLE
Can't load pretrained weight - `HTTP Error 403: Forbidden`

### ISSUE THREAD

**Issue by ongss** [lukemelas/EfficientNet-PyTorch#145]
Hello @lukemelas 
In [Example file](https://github.com/lukemelas/EfficientNetPyTorch/blob/master/examples/simple/example.ipynb), `model = EfficientNet.from_pretrained(model_name)` It has HTTP Error 403. 
Any suggestions on this issue? Can I access pretrained model?

**Comment by lukemelas** [comment]
Have you updated the repo? Note the (italicized and uppercased) note at the top of the README.: 

> IMPORTANT NOTE: In the latest update, I switched hosting providers for the pretrained models, as the previous models were becoming extremely expensive to host. This will break old versions of the library. I apologize, but I cannot afford to keep serving the models on the old provider. Everything should work properly if you update the library:
> `pip install --upgrade efficientnet-pytorch`

**Comment by ongss** [comment]
It's my bad. I forgot to update the repo.
Thank you for helping.

**Comment by akashdeepjassal** [comment]
@lukemelas  Wouldn't it be better if you release those using GitHub releases ?
