### ISSUE TITLE
Slow download mirrors through windows.net

### ISSUE THREAD

**Issue by sleeplessai** [lukemelas/EfficientNet-PyTorch#148]
I notice downloading through the `windows.net` mirror is unstably slow.
It is better to get the pre-trained weights from google drive.

`
url_map = {
    'efficientnet-b0': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b0-355c32eb.pth',
    'efficientnet-b1': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b1-f1951068.pth',
    'efficientnet-b2': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b2-8bb594d6.pth',
    'efficientnet-b3': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b3-5fb5a3c3.pth',
    'efficientnet-b4': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b4-6ed6700e.pth',
    'efficientnet-b5': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b5-b6417697.pth',
    'efficientnet-b6': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b6-c76e70fd.pth',
    'efficientnet-b7': 'https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b7-dcc49843.pth',
}
`

**Comment by lukemelas** [comment]
I'm working on it. Thanks to some help from Google we'll have fast downloads again soon.

**Comment by sleeplessai** [comment]
Thanks for that.

**Comment by lukemelas** [comment]
Fixed! I'm closing this issue -- reopen if you encounter problems :)

**Comment by sleeplessai** [comment]
@lukemelas updated v0.6.3 and found them available on github.com. change works. 😊
