### ISSUE TITLE
convert Tensorflow weights to Pytorch

### ISSUE THREAD

**Issue by xbpgithub** [lukemelas/EfficientNet-PyTorch#15]
Hi, I can't download the Tensorflow weights form the URL in your code, so I download the weights myself. I also want to use your code to convert the tensorflow weights to Pytorch, what should I do?

**Comment by lukemelas** [comment]
Hello, 

Did you see the README in the `tf_to_pytorch` folder? If you have questions, let me know!

**Comment by xbpgithub** [comment]
Thank you very much, it's my fault. 
I have solved the problem

**Comment by lukemelas** [comment]
Good to hear, and thanks for updating the issue.
