### ISSUE TITLE
About pretrainted model

### ISSUE THREAD

**Issue by GETUNTUN** [lukemelas/EfficientNet-PyTorch#150]
I can't download the pretrainted model from the url now.
http://storage.googleapis.com/public-models/efficientnet/efficientnet-b0-355c32eb.pth

**Comment by maxjeblick** [comment]
Also getting HTTPError: HTTP Error 403: The specified account is disabled.

**Comment by rafiko1** [comment]
I'm also getting the same error. Any fix for that?

**Comment by bsridatta** [comment]
Same here!

**Comment by b02202050** [comment]
Hi everyone, I found a useful [pretrained weight links](https://www.kaggle.com/hmendonca/efficientnet-pytorch) that some kind man uploaded to kaggle.
* Note that you have to modify the *load_pretrained_weights* function in *utils.py* as following:
delete `state_dict = model_zoo.load_url(url_map_[model_name])`
add `state_dict = torch.load(<pretrained weight file path>, map_location='cpu')`

**Comment by Kaushal28** [comment]
@b02202050 Thanks for pointing out the Kaggle Dataset. Here is how you do it dynamically in your code:

```
def custom_load_pretrained_weights(model, model_name, load_fc=True, advprop=False):
    """ Loads pretrained weights, and downloads if loading for the first time. """
    # AutoAugment or Advprop (different preprocessing)
    url_map_ = url_map_advprop if advprop else url_map
    state_dict = torch.load('/content/efficientnet-b1-dbc7070a.pth', map_location='cpu')
    if load_fc:
        model.load_state_dict(state_dict)
    else:
        state_dict.pop('_fc.weight')
        state_dict.pop('_fc.bias')
        res = model.load_state_dict(state_dict, strict=False)
        assert set(res.missing_keys) == set(['_fc.weight', '_fc.bias']), 'issue loading pretrained weights'
    print('Loaded pretrained weights for {}'.format(model_name))

from efficientnet_pytorch import utils
utils.load_pretrained_weights.__code__ = custom_load_pretrained_weights.__code__
```

After patching the function, use the library as it is. Just for information tagging: @maxjeblick @rafiko1 @bsridatta

**Comment by lukemelas** [comment]
I'm sorry about this everyone. My hosting was shut down (again) due to excessive downloads. 

I've reached out to Google about this and they've generously offered to host the pretrained weights for me, so that I won't have to pay for them myself anymore. Fix coming today!

**Comment by qubvel** [comment]
Why not to host weights in GitHub releases?(e.g. Keras do it that way, and I also use it)

All you need is to create a release and attach weight files

**Comment by lukemelas** [comment]
Okay, updated! This issue should be fixed, let me know if there are any more issues. 

@qubvel I'm now using GitHub releases :)

**Comment by lukemelas** [comment]
I'm closing this issue -- reopen if you encounter problems :)

**Comment by mcombalia** [comment]
Hello,

I am finding again the same problem when downloading Effnet b0 weights.

HTTPError: HTTP Error 403: The specified account is disabled.

Thanks

**Comment by Kaushal28** [comment]
@mcombalia Try upgrading the library using `pip install --upgrade efficientnet-pytorch`

**Comment by abdulsamadzahir** [comment]
@Kaushal28 That's a great workaround! Solves it for me. Thanks
