### ISSUE TITLE
Simple example for transfer learning

### ISSUE THREAD

**Issue by boulabiar** [lukemelas/EfficientNet-PyTorch#152]
What's the best way to do transfer learning for image classification.
If I choose a pre-trained model with 20 classes, then which part should I train?
Should I remove the last layer? or keep it and add other ones so that they will be trained?

**Comment by lukemelas** [comment]
Yes, I'd remove the last layer and replace it with a randomly-initialized one with output dimension 20. This is all done automatically with: 
```
EfficientNet.from_pretrained('efficientnet-b0', num_classes=20)
```

**Comment by lukemelas** [comment]
Re-open this if you have any more questions.

**Comment by boulabiar** [comment]
And what's the Python line to fix parameters on all layers except that last one?

What I did is computing the number of layers in a debug code then in a for loop, testing if I reached layer 253 (not sure about that number) then not making that layer fixed.
Which I think it's not the best way to do it...

**Comment by lukemelas** [comment]
You can freeze all the parameters and then unfreeze the last layer: 
```
for param in model.parameters():
    param.requires_grad = False
model. _fc.requires_grad = True
```

**Comment by lkevinzc** [comment]
> You can freeze all the parameters and then unfreeze the last layer. In essence:
> 
> ```
> for param in model.parameters():
>     param.requires_grad = False
> model._fc.requires_grad = True
> ```
> 
> I think in reality you probably have to do the last line for both `_fc.weight` and `fc.bias`

Hi there~ I'm also about to do a transfer learning, but the data is quite different. Any suggestions on where should I freeze the parameters from? like in ResNet people usually freeze the first layer, second layer, etc. But in EffecientNet there are only a bunch of blocks

Thank~
