### ISSUE TITLE
Speed problem

### ISSUE THREAD

**Issue by AllentDan** [lukemelas/EfficientNet-PyTorch#159]
Really helped a lot from your code. However, I found that even EfficientNetB0 is still slower than inception-v3. Here is my  comparison:
on CPU, it cost 0.62s for EfficientNetB0 to forward a tensor([1,3,224,224]).
In the same environment, it cost 0.23s for inception-v3 to forward a tensor([1,3,224,224]).
According to the published paper, I thought EfficientNet should be faster than Inception. This confused me a lot. It will be appreciated if you reply. Thank you again. @lukemelas

**Comment by SHENG-KAI-HUANG** [comment]
I think maybe the reason is the depth-wise convolution in pytorch is slow, like discuss [here](https://discuss.pytorch.org/t/no-speedup-with-depthwise-convolutions/36847)

**Comment by lukemelas** [comment]
Redirecting this to #10
