### ISSUE TITLE
pretrained efficientnet-b7 ?

### ISSUE THREAD

**Issue by cdluminate** [lukemelas/EfficientNet-PyTorch#16]
Hi, thank you for the awesome work. May I ask whether you have plan to provide the pre-trained efficientnet-b7 model?

**Comment by lukemelas** [comment]
Thanks for the question! Yes, the plan certainly involves releasing a pretrained B7 model. 

At the moment, we are working on reproducing the original results (without the TensorFlow weights) by training in PyTorch -- it's trickier than it seems, as there are a number of training nuances and TensorFlow-specific tricks (i.e. model weight EWA). 

When we've got training working on the small models, we'll train a B7 model. Of course, if the original authors ever release a B7 model in TensorFlow, you'll see it here immediately :). 

Keeping this issue open for the time being.

**Comment by cdluminate** [comment]
great! Please keep up your good work and it's much appreciated.

**Comment by lukemelas** [comment]
Thought I's update this: B4 and B5 are now available. 

B7 is not out yet, but it will be at some point soon.

**Comment by arrufat** [comment]
Hi! It seems like they're available now: https://twitter.com/quocleix/status/1156334264322940928

**Comment by lukemelas** [comment]
Great! Expect them soon.

**Comment by lukemelas** [comment]
Done! 

Let me know if there are any issues.
