### ISSUE TITLE
EfficientNET.onnx does not run in TensorRT

### ISSUE THREAD

**Issue by Soroorsh** [lukemelas/EfficientNet-PyTorch#167]
Hi, 
I've got this error for running the converted EfficientNet from PyTorch to Onnx in TensorRT:

```
Traceback (most recent call last):
  File "tensorrt_python.py", line 59, in <module>
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

Can anybody help me? 

TensorRT version: 6.1.05
Pytorch: 1.1.0
Onnx: 1.5.0

**Comment by MartinBrazdil** [comment]
There was an error during engine creation hence engine is None. You have to provide more information how your engine is created because engine creation can fail for various reasons.

**Comment by VCBE123** [comment]
> There was an error during engine creation hence engine is None. You have to provide more information how your engine is created because engine creation can fail for various reasons.

See, I convert b2 model to onnx and check results, It looks good.
But when I load the onnx model using tensorRT， it outputs many warnings and costs much longer time than convert resnet50.
![image](https://user-images.githubusercontent.com/30370620/79531670-a4bc8980-80a5-11ea-9dce-cba9fb233101.png)
![image](https://user-images.githubusercontent.com/30370620/79531795-efd69c80-80a5-11ea-954a-ae0a26e9ae8d.png)


Note the environment : 
Windows 10 x64   GPU 1650 CUDA10,  pytorch 1.1.0 TensorRT 7.0

The output logits are different from the onnx out ( which are the same as pytorch ).

I also try to read some documents about tensorRT， But can not solve this issue.

**Comment by Soroorsh** [comment]
> There was an error during engine creation hence engine is None. You have to provide more information how your engine is created because engine creation can fail for various reasons.

I use tensorRT python sample for creating the engine. 

```
def build_engine_onnx(model_file):
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network, trt.OnnxParser(networ$
        builder.max_workspace_size = common.GiB(1)
        builder.max_batch_size =32
        # Load the Onnx model and parse it in order to populate the TensorRT network.
        with open(model_file, 'rb') as model:
            parser.parse(model.read())
```

I had a problem with converting the EfficientNet from PyTorch to ONNX.  ONNX can't export SwishImplementation. I use this line to convert. 

`model.set_swish(memory_efficient=False)`

Is it possible this layer causes the problem?

**Comment by Soroorsh** [comment]
Finally, I could run the efficientNet model using this environment:

```
TensorRT 7
ONNX 1.5.0
Pytorch 1.3.0
torchvision=0.4.2
```

**Comment by DecentMakeover** [comment]
@Soroorsh  hey did you give any output names? i am getting the same error

**Comment by Soroorsh** [comment]
> @Soroorsh hey did you give any output names? i am getting the same error

Hey, 
I'm sorry for the belated answer, 
I've used this code: 
`  model_name = 'efficientnet-b0'
    model = EfficientNet.from_pretrained(model_name)
    model.set_swish(memory_efficient=False)
    model.eval()
    dummy_input = torch.randn(1, 3, 224, 224)
    torch.onnx.export(model, dummy_input, "efficientnet-b0.onnx",['input0'])`

**Comment by kochsebastian** [comment]
Do you get non zero outputs when do inference with TensorRT.   
For me at least although it converts fine to TensorRT my outputs are always zero.

Using a trained network and a real image for onnx conversion. Infeence in PyTorch and onnx works but for the same input in TensorRT I always get a 0 tensor

**Comment by pshwetank** [comment]
@kochsebastian Even I am facing the same issue with TensorRT model. As soon as I convert the onnx model to tensorRT version, the performance drops completely.
