### ISSUE TITLE
Convert to Onnx Collab notebook fails on torch.onnx.export(..)

### ISSUE THREAD

**Issue by shubham-samant** [lukemelas/EfficientNet-PyTorch#170]
Hi i wanted to convert the model to onnx format, i tried the collab notebook, however the code fails at the conversion step - torch.onnx.export(..) Can u please look into this ? Thanks!

**Comment by ZHUTAO142857** [comment]
I met the same problem, I tried b0, b1, b4, b5, but thay all failed to produce an onnx file.

**Comment by tom-garford** [comment]
Hi, 

I also have the same problem on my local machine. Tried with torch 1.2 as well as 1.4 but makes on difference. No onnx file written and no error (verbose output given appears to show onnx conversion has been successful). 
Changing path in torch.onnx.export to something invalid also makes no difference, no error given.

**Comment by tom-garford** [comment]
This worked for me: 

`import torch 
from efficientnet_pytorch import EfficientNet

print(torch.__version__)

with torch.cuda.device(0):
    with torch.no_grad():
        model = EfficientNet.from_pretrained('efficientnet-b5')
        dummy_input = torch.randn(10, 3, 240, 240)
        model = model.cuda()
        model.set_swish(False)
        dummy_input = dummy_input.cuda().float()
        input_names = ["input0"]
        torch.onnx.export(model, dummy_input, "/home/tom/EfficientNet-PyTorch/test-b5.onnx", opset_version=11, 
        export_params=True, verbose=False, input_names=input_names)

`

**Comment by tom-garford** [comment]
![Screenshot from 2020-04-25 10-53-22](https://user-images.githubusercontent.com/57392179/80276828-06eb3f00-86e3-11ea-9a11-ddf4278c8898.png)

**Comment by shubham-samant** [comment]
>
