### ISSUE TITLE
Conv2dStaticSamePadding uses incorrect image size

### ISSUE THREAD

**Issue by mannatsingh** [lukemelas/EfficientNet-PyTorch#177]
I just want to start by saying that this is a great implementation, @lukemelas ! 
While looking at the code, I realized that there's an issue in the image size used by all the conv modules when static padding is used. [`Conv2d = get_same_padding_conv2d(image_size=global_params.image_size)
 `](https://github.com/lukemelas/EfficientNet-PyTorch/blob/master/efficientnet_pytorch/model.py#L122) fetches the conv operator once based on the original image size and the same operator is used everywhere. But the image size changes inside the model, so the padding turns out to be incorrect.

I am one of the authors of [Classy Vision](https://github.com/facebookresearch/ClassyVision), you could check out our [EfficientNet implementation](https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/models/efficientnet.py) to see what I mean.

**Comment by curiositywan** [comment]
Noticed the same issue. Looks like except the first conv, all the others should use Conv2dDynamicSamePadding.

**Comment by lukemelas** [comment]
Hi @mannatsingh, thank you for the issue! I appreciate you bringing this to my attention. I've addressed it in #179. Let me know if you see any more issues with the model.

Also Classy Vision is great! Thanks for your work on it.

**Comment by mannatsingh** [comment]
Thanks @lukemelas for addressing this so quickly!

Also, we'd love your feedback in case you ever get a chance to try out Classy Vision :)
