### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by mxtsai** [lukemelas/EfficientNet-PyTorch#18]
Hi Luke,

Thank you for the awesome work. I tried running EfficientNet-B0 on my GTX 1070 (8GB RAM) with an input batch of dimension [44x1x256x256] (single channel image) and I am running into 'CUDA out of memory' (with the model in 'training' mode). 

I tried running [another implementation](https://github.com/zsef123/EfficientNets-PyTorch) and wasn't getting this issue, and after digging in the code, it seems as if the implementation for MBConv (or the re-iteration of MBConv) was too memory hungry.

 I really like your implementation of EfficientNet and if I did have more time, I would definitely have a deeper dive into your code. At the mean time, if possible, could you help me check this issue out (maybe it'll speed up training in the future?) ? Thank you!

**Comment by lukemelas** [comment]
Hello, thanks for filing the issue. I'll look into it this weekend.

**Comment by jlevy44** [comment]
I think I'm running into a similar issue as well.

**Comment by crazyblacker** [comment]
I meet the same issue when I exchange backbone with B3. Model size become smaller but out of memory on  my 2080Ti(11G).

**Comment by dami23** [comment]
Hi @lukemelas. Thank you for your awesome work. I find the newly released version requires more GPU  memory than the original one. The same project use B3 model can be run with the older version, but after the upgrade, this code cannot be run anymore and with error"RuntimeError: CUDA out of memory". Could you please give me any advices to face this problem? Thank you!!

**Comment by lukemelas** [comment]
Hi @dami23 , that's strange because nothing about the B3 model changed in any way during the update (apart from the addition of `drop_connect`). In fact, you can see all the changes that were made here: https://github.com/lukemelas/EfficientNet-PyTorch/commit/9a0d45fa4474bbc79ef29348cafcdfccba2e41d6

Can you try measuring memory usage with the two versions to confirm the issue?

**Comment by xbpgithub** [comment]
Hello，I also meet the similar memory issue. EfficinetNet-b3 consumes more memory than Resnet50 for FPN, is it normal? Can someone provide some help?

**Comment by twmht** [comment]
any update on this?

**Comment by seilna** [comment]
Similar problems with @xbpgithub, and it seems that in `MBConvBlock()`, `relu_fn(x)` and `self._bn` are memory bottleneck. Replacing them with [Inplace BatchNorm](https://github.com/mapillary/inplace_abn) was helpful to significantly reduce memory usage, but until now, it does not support swish activation function.
(I'm not sure it is right direction to focus on batchnorm to reduce memory usage, but hope it can be helpful)

**Comment by seilna** [comment]
I also observed that in `relu_fn()`, using **custom op** for swish activation function (instead of `return x * torch.sigmoid(x)`) was helpful to reduce memory usage (up to 30%) as follows:

```
sigmoid = torch.nn.Sigmoid()
class Swish(torch.autograd.Function):
    @staticmethod
    def forward(ctx, i):
        result = i * sigmoid(i)
        ctx.save_for_backward(i)
        return result

    @staticmethod
    def backward(ctx, grad_output):
        i = ctx.saved_variables
        sigmoid_i = sigmoid(i)
        return grad_output * (sigmoid_i * (1 + i * (1 - sigmoid_i)))

swish= Swish.apply

class Swish_module(nn.Module):
    def forward(self,x):
        return swish(x)

swish_layer = Swish_module()
def relu_fn(x):
    """ Swish activation function """
    # return x * torch.sigmoid(x)
    return swish_layer(x)
```

**Comment by jackytu256** [comment]
@seilna 
perhaps, the h-swish (provided by MobilenetV3) may be another option to deal with this issue?

```python
class h_sigmoid(nn.Module):
    def __init__(self, inplace=True):
        super(h_sigmoid, self).__init__()
        self.relu = nn.ReLU6(inplace=inplace)

    def forward(self, x):
        return self.relu(x + 3) / 6


class h_swish(nn.Module):
    def __init__(self, inplace=True):
        super(h_swish, self).__init__()
        self.sigmoid = h_sigmoid(inplace=inplace)

    def forward(self, x):
        return x * self.sigmoid(x)


```
![alt text](https://storage.googleapis.com/groundai-web-prod/media%2Fusers%2Fuser_15628%2Fproject_360055%2Fimages%2Fx6.png)

**Comment by psinger** [comment]
I am also wondering if there is a memory leak? Even after deleting the model, my GPU memory does not clear. I tried the exact same training routine I use for Efficient Net with a ResNet and there I don't have this issue. This basically makes it impossible for me to train multiple models after each other. Does anyone have any idea what can be the reason for it?

**Comment by tmabraham** [comment]
Any update on this? @DrHB mentioned this over [here](https://www.kaggle.com/c/rsna-intracranial-hemorrhage-detection/discussion/111292#latest-641437) and it would be nice if this repository was updated with this fix.

**Comment by lukemelas** [comment]
The latest version of the repo (released a week ago) should fix this issue! 

A memory-efficient swish function is now used by default. However, this swish function is incompatible with model exporting (ONNX), so you also have the option of using `model.set_swish(memory_efficient=False)`.

**Comment by jinfagang** [comment]
@lukemelas  Is that a way to make ONNX also memory efficient?

**Comment by lukemelas** [comment]
Closing this issue, as it was resolved in 2019
