### ISSUE TITLE
EfficientNet without Top Layers

### ISSUE THREAD

**Issue by nhorangl** [lukemelas/EfficientNet-PyTorch#192]
I tried to remove top layers like follows:

base_model = EfficientNet.from_pretrained('efficientnet-b3')
model = nn.Sequential(*list(base_model.children()[:-3]))

x = torch.randn((1,3,300,300))
model(x)

It throws "NotImplementedError" for forward(). Is there a way to not include top layers?

**Comment by Cyril9227** [comment]
Overwrite the forward method to yield the features map of the desired layer

**Comment by nwschurink** [comment]
Yes, or add an option to the initialization of the network that allows dropping these layers (similar to how EfficientNet is implemented in Tensorflow).
I made the adjustments for a EfficientNet3D fork of this repo -> see pull request here https://github.com/shijianjian/EfficientNet-PyTorch-3D/pull/4 
If you want I can also change the code for this repo and post a pull request here

**Comment by 23pointsNorth** [comment]
@nwschurink 's solution is much better, but in the mean time, an alternative is to substitute them with Identity layers:

```
model._fc = nn.Identity()
model._swish = nn.Identity()
```

**Comment by lukemelas** [comment]
This is now integrated :)

**Comment by 23pointsNorth** [comment]
@lukemelas is it going to be in the next pip version? Or do you know when it's planned for release?
