### ISSUE TITLE
EfficientNet-b0 slower than Resnet-50?

### ISSUE THREAD

**Issue by cgebbe** [lukemelas/EfficientNet-PyTorch#195]
I wrote a small script to check inference and training speed of efficientnet vs. Resnets. According to these results, the efficient-b0 is measurably slower than resnet-50 ?!? Am I doing something wrong? 

Using version 0.4.1 (GPU V100)
> === Checking effnetb0
> inference time=19.62038330078125
> train time=70.4931103515625
> === Checking resnet18
> inference time=3.7844888305664064
> train time=20.64025634765625
> === Checking resnet50
> inference time=11.5154638671875
> train time=56.6721044921875

Using version 1.4.0 (local GPU M2200)

> === Checking effnetb0
> inference time=45.6470166015625
> train time=215.383828125
> === Checking resnet18
> inference time=11.30126220703125
> train time=57.34619140625
> === Checking resnet50
> inference time=27.5243359375
> train time=151.6120703125

//EDIT:
- probably related to https://github.com/lukemelas/EfficientNet-PyTorch/issues/19
- XXX

Script is below
```
import torchvision
import efficientnet_pytorch
import torch


models = {}
models['effnetb0'] = efficientnet_pytorch.EfficientNet.from_pretrained("efficientnet-b0")
models['resnet18'] = torchvision.models.resnet18(pretrained=False)
models['resnet50'] = torchvision.models.resnet50(pretrained=False)


device = 'cuda'
t_in = torch.randn(1, 3, 224, 224, device=device)
for name, model in models.items():
    # set model to eval
    model.to(device)
    print("=== Checking {}".format(name))

    # do warmup
    print("do warmup")
    for i in range(100):
        t_out = model.forward(t_in)

    # do inference
    print("measure inference")
    model.eval()
    navrg = 100
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    for i in range(navrg):
        t_out = model.forward(t_in)
    end.record()
    torch.cuda.synchronize()
    t_in_ms = start.elapsed_time(end)
    print("inference time={}".format(t_in_ms/navrg))

    # train time
    print("measure train")
    model.train()
    navrg = 100
    optimizer = torch.optim.Adam(model.parameters())
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    for i in range(navrg):
        t_out = model.forward(t_in)
        loss = torch.mean(t_out)**2
        loss.backward()
        optimizer.step()
    end.record()
    torch.cuda.synchronize()
    t_in_ms = start.elapsed_time(end)
    print("train time={}".format(t_in_ms/navrg))



```

**Comment by lukemelas** [comment]
Yes, this is a known issue with PyTorch. Hopefully the fp32 depthwise convolutions will be fast in PyTorch soon (it's on the roadmap I believe, maybe even in 1.6 or 1.7). 

Closing this because it's the save as #19 (I believe, correct me if wrong).

**Comment by siarez** [comment]
Is this addressed? 
My B0 is still slower than ResNet50 by a factor of ~2.
I'm on Torch=1.10.0+cu113

**Comment by seann999** [comment]
Still having this problem with pytorch 2
