### ISSUE TITLE
which part has been changed to speed the inference?

### ISSUE THREAD

**Issue by kaixin-bai** [lukemelas/EfficientNet-PyTorch#196]
ubuntu 18.04
GPU: GeForce GTX 1070

issues [19](https://github.com/lukemelas/EfficientNet-PyTorch/issues/19
) mentioned that the pytorch efficientnet inference is much slower than original tensorflow version. But i test the example code with:
```
with torch.no_grad():
    while True:
        start = time.time()
        logits = model(img)
        print("cost:", time.time()-start)
```
and got:
```
Loaded pretrained weights for efficientnet-b0
cost: 0.030891895294189453
cost: 0.020551681518554688
cost: 0.020317554473876953
cost: 0.020257949829101562
cost: 0.0203554630279541
cost: 0.02055835723876953
cost: 0.020155668258666992
cost: 0.020232200622558594
```
It is much faster, which part has been changed to fix this?

**Comment by lukemelas** [comment]
What version of PyTorch are you on?

**Comment by kaixin-bai** [comment]
# Name                    Version                   Build  Channel
pytorch                   1.5.0           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch

**Comment by francisco-simoes** [comment]
Any updates on this?
