### ISSUE TITLE
Fix link in readme to TF implementation

### ISSUE THREAD

**Issue by impredicative** [lukemelas/EfficientNet-PyTorch#2]
> Our PyTorch model model is consistent with the original TensorFlow implementation

Copy pasting is dangerous.

**Comment by lukemelas** [comment]
Thanks! Done.

**Comment by impredicative** [comment]
Really? Why are you rushing so much and not checking your work?

> It is consistent with the [original TensorFlow implementation]()

**Comment by lukemelas** [comment]
Apologies, I only saw the fact that the word "model" was duplicated. The link is now updated as well. Thanks for pointing out the issues.
