### ISSUE TITLE
How to tranform efficient-pytorch to efficient-onnx

### ISSUE THREAD

**Issue by peyer** [lukemelas/EfficientNet-PyTorch#20]
I have tried to convert efficient-pytorch to efficient-onnx with api (torch.onnx.export), but I meet a problem showing below info
Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible
How could I fix it ?

**Comment by lukemelas** [comment]
Yes, I can try to make the kernel size static in the next significant update.

**Comment by peyer** [comment]
@lukemelas Thansk!

**Comment by lukemelas** [comment]
Done! I had to change some things with the padding, so it took a little while. 

Here is an example: 
https://colab.research.google.com/drive/1rOAEXeXHaA8uo3aG2YcFDHItlRJMV0VP

**Comment by lukemelas** [comment]
Closing this issue, but definitely re-open if you have any issues.

**Comment by peyer** [comment]
@lukemelas Successd and thanks!

**Comment by lukemelas** [comment]
Great to hear!

**Comment by cham-3** [comment]
> Done! I had to change some things with the padding, so it took a little while.
> 
> Here is an example:
> https://colab.research.google.com/drive/1rOAEXeXHaA8uo3aG2YcFDHItlRJMV0VP

I run the example, but it raised the following error.

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-64a7fa550fc1> in <module>()
     13 
     14 # Export with ONNX
---> 15 torch.onnx.export(model, dummy_input, "efficientnet-b1.onnx", verbose=True)

2 frames
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, enable_onnx_checker, use_external_data_format)
    501                 params_dict, opset_version, dynamic_axes, defer_weight_export,
    502                 operator_export_type, strip_doc_string, val_keep_init_as_ip, custom_opsets,
--> 503                 val_add_node_names, val_use_external_data_format, model_file_location)
    504         else:
    505             proto, export_map = graph._export_onnx(

RuntimeError: ONNX export failed: Couldn't export Python operator SwishImplementation
`

**Comment by deepconsc** [comment]
@lukemelas Hey! Appreciate your great work.
For the latest version, exporting to onnx fails due to Swish. Any ideas?

**Comment by kendyChina** [comment]
@bkhti4 Thanks! When I replaced SwishImplementation() with Swish(), I converted the model to onnx successfully.

**Comment by lukemelas** [comment]
How there's `nn.SiLU` as well, so I believe all models should be memory-efficient and exportable :) 

The older functions are still included for backward compatibility with old versions of PyTorch

**Comment by fangliang425** [comment]
@lukemelas Hi, when I simply ran 
```
model = EfficientNet.from_name(model_name='efficientnet-b0')
model.eval()
model.set_swish(memory_efficient=False)
torch.onnx.export(model, torch.rand(10, 3, 240, 240), "EfficientNet-B0.onnx")
```
, and got error as blow, any ideas? Thanks.
`RuntimeError: Exporting the operator silu to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.`

environment: 
Ubuntu 20.04
torch 1.7.1 
cuda 11.0
efficientnet-pytorch 0.7.1

**Comment by louisnt-prod** [comment]
> @lukemelas Hi, when I simply ran
> 
> ```
> model = EfficientNet.from_name(model_name='efficientnet-b0')
> model.eval()
> model.set_swish(memory_efficient=False)
> torch.onnx.export(model, torch.rand(10, 3, 240, 240), "EfficientNet-B0.onnx")
> ```
> 
> , and got error as blow, any ideas? Thanks.
> `RuntimeError: Exporting the operator silu to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.`
> 
> environment:
> Ubuntu 20.04
> torch 1.7.1
> cuda 11.0
> efficientnet-pytorch 0.7.1

Same here, if you found a solution since I'm all ears :)

**Comment by aojue1109** [comment]
> @lukemelas嗨，当我简单地跑步时
> 
> ```
> model = EfficientNet.from_name(model_name='efficientnet-b0')
> model.eval()
> model.set_swish(memory_efficient=False)
> torch.onnx.export(model, torch.rand(10, 3, 240, 240), "EfficientNet-B0.onnx")
> ```
> 
> ，并因错误而遭受打击，有什么主意吗？谢谢。
> `RuntimeError: Exporting the operator silu to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.`
> 
> 环境：
> Ubuntu 20.04
> 火炬1.7.1
> cuda 11.0
> 高效net-pytorch 0.7.1

Is it resolved? I need your help！

**Comment by chilin0525** [comment]
@aojue1109  I converted the model to onnx successfully. There's my [gist link](https://gist.github.com/chilin0525/f5e2ddbca60ef154c182d0c77d591ca4). 
If still not solve your problem I think you should re-open the issue.

**Comment by dgdgksj** [comment]
@chilin0525  I had a hard time exporting efficient net to onnx, but I see your code and solve it Thank you

**Comment by dgdgksj** [comment]
@chilin0525 thanks!!
