### ISSUE TITLE
Anyone achieved about 77% on imagenet with eff-b0??

### ISSUE THREAD

**Issue by ooodragon94** [lukemelas/EfficientNet-PyTorch#202]
Hello peop!
I'm wondering if anyone did achieve 77% with effb0 on imagenet
If you did can you share your settings? (lr - 0.1, scheduler, etc)

**Comment by lg920810** [comment]
I tried cosine lr schedule but just get the top-1 70.9. Do you have any idea for reproducing the accuracy?

**Comment by Christian-lyc** [comment]
Me too. I also couldn't reproduce the results. Did you solve it?

**Comment by ooodragon94** [comment]
Not really
But I think I was able to get similar result with using RMSProp and EMA
