### ISSUE TITLE
Testing results on ImageNet-1k val,  224-crop@256-image,  320-crop@350-image

### ISSUE THREAD

**Issue by zhjpqq** [lukemelas/EfficientNet-PyTorch#21]
I evaluate the pre-trained EfficientNet  on ImageNet-1k val:

| model  | depth  |  params  |  flops  |  224-crop @ 256-img  |  320-crop @ 350-img  |
| ------------ | ------------ | ------------ | ------------ | ------------ | ------------ |
| eff-b0  | 82  | 5.28M  | 0.778G  | 75.880 / 92.758  | 78.286 / 94.108  |
| eff-b1  | 116  | 7.79M  | 1.148G  | 76.622 / 93.232  | 79.736 / 94.930  |
| eff-b2  | 116  | 9.11M  | 1.327G  | 76.484 / 92.932  | 80.110 / 95.038  |
| eff-b3  | 131  | 12.23M  | 1.938G  | 75.964 / 92.888  | 80.700 / 95.204  |

For more details:   http://studyai.com/article/1f9d25de

The results are very different with paper.  Does anybody get better results ？

**Comment by zhjpqq** [comment]
`224/0.875=256`  `224/0.7=320`  `240/0.7=342` `260/0.7=372`  `300/0.7=428`

| model    |  224@224-BICUBIC  |  320@320-BICUBIC  |  224@224/0.875-BICUBIC  | 320@320+32-BICUBIC  |
| ------------ | ------------ | ------------ | ------------ |
| eff-b0  |  -  / - | `78.628 / 94.382`  |  - / -  |  - / - |

| model    |  240@240-BICUBIC  |  342@342-BICUBIC  |  240@240/0.875-BICUBIC  | 342@342/0.875-BICUBIC  |
| ------------ | ------------ | ------------ | ------------ |
| eff-b1  |  78.204  / 93.896 | `80.186 / 95.206`  |  - / -  |  - / - |

| model    |  260@260-BICUBIC  |  372@372-BICUBIC  |  372@372/0.875-BICUBIC  | 372@372+32-BICUBIC  |
| ------------ | ------------ | ------------ | ------------ |
| eff-b2  |  79.336  / 94.650 | `81.132 / 95.540`  |  80.852 / 95.334  |  81.036 / 95.466 |

| model    |  300@300-BICUBIC  |  428@428-BICUBIC |  300@300/0.875-BICUBIC  |  320@320+32-BICUBIC |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| eff-b3  |  80.782 /  95.246  |  `82.270 / 96.014`  |  80.836 / 95.294  |  81.148  / 95.428  |

**Comment by zhjpqq** [comment]
224/0.7=320  260/0.7=372  300/.7=428

model  260@260-BICUBIC               372@372-BICUBIC
effb2  prec@1-79.336 prec@5-94.650   prec@1-81.132 prec@5-95.540
model  300@300-BICUBIC               428@428-BICUBIC
effb3  prec@1-80.782 prec@5-95.246   prec@1-82.270 prec@5-96.014

http://studyai.com/article/1f9d25de

**Comment by zhjpqq** [comment]
BICUBIC  is better than BILINEAR !!!

| model    |  260@260-BICUBIC  |  372@372-BICUBIC  |  372@372/0.875-BICUBIC  | 372@372+32-BICUBIC  |
| ------------ | ------------ | ------------ | ------------ |
| eff-b2  |  79.336  / 94.650 | `81.132 / 95.540`  |  80.852 / 95.334  |  81.036 / 95.466 |

Using  image_size/0.7  can get better performance than paper.

| model    |  300@300-BICUBIC  |  428@428-BICUBIC |  300@300/0.875-BICUBIC  |  320@320+32-BICUBIC |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| eff-b3  |  80.782 /  95.246  |  `82.270 / 96.014`  |  80.836 / 95.294  |  81.148  / 95.428  |

**Comment by zhjpqq** [comment]
| model    |  224@224  |  320@320  |  224@224/0.875  | 320@320+32  |
| ------------ | ------------ | ------------ | ------------ |
| eff-b0  |  75.884  / 92.722 | `78.628 / 94.382`  |  - / -  |  - / - |
| -    |  240@240  |  342@342  |  240@240/0.875  | 342@342/0.875  |
| eff-b1  |  78.204  / 93.896 | `80.186 / 95.206`  |  - / -  |  - / - |
| -    |  260@260  |  372@372  |  372@372/0.875  | 372@372+32  |
| eff-b2  |  79.336  / 94.650 | `81.132 / 95.540`  |  80.852 / 95.334  |  81.036 / 95.466 |
| -    |  300@300  |  428@428 |  300@300/0.875  |  320@320+32 |
| eff-b3  |  80.782 /  95.246  |  `82.270 / 96.014`  |  80.836 / 95.294  |  81.148  / 95.428  |

**Comment by zhjpqq** [comment]
The FLOPs results  is also  differtent from paper.   My code is avaliable  at  http://studyai.com/article/a718990b
welcome to discuss.

**Comment by zhjpqq** [comment]
For some paper, the "multiply_adds==True", 
while for other papers the "multiply_adds==False".
In usual,  the FLOPs  under "True"  is  2x  the  FLOPs  under "False".
code is here:  http://studyai.com/article/a718990b

Under "multiply_adds==False",  the results are below, which are the same to paper.

### model   depth    param     GFLOPs 
### effb0    82l        5.28M     0.393G 
### effb1    116L     7.79M     0.697G 
### effb2    116L     9.11M     1.007G
### effb3    131L     12.23M   1.851G
### effb4    161L    19.34M    4.443G

**Comment by lukemelas** [comment]
Closing this issue, but definitely re-open it if you feel there is still more to investigate/discuss!
