### ISSUE TITLE
Conversion to Pytorch Mobile

### ISSUE THREAD

**Issue by TomekPro** [lukemelas/EfficientNet-PyTorch#218]
Hi I'm trying to convert pretrained EfficientNet model to Pytorch Mobile. I follow official instructions from [here](https://pytorch.org/mobile/home/). While scripting model using: scripted_model = torch.jit.script(model) I get:
"Tried to access nonexistent attribute or method 'saved_variables' of type '__torch__.efficientnet_pytorch.utils.SwishImplementation'. Did you forget to initialize an attribute in __init__()?:"

I'm new to PyTorch, maybe someone knows this issue or can hint me how to fix it?

![image](https://user-images.githubusercontent.com/49069202/89415158-c95b7080-d72b-11ea-821f-4680e9e73eec.png)

Code to reproduce:
```
from efficientnet_pytorch import EfficientNet
import torch

model = EfficientNet.from_pretrained('efficientnet-b0')
scripted_model = torch.jit.script(model)
```

Environment:
```
efficientnet-pytorch      0.6.3                    pypi_0    pypi
pytorch                   1.6.0           py3.6_cuda102_cudnn7_0    pytorch
```

Thanks
Tomek

**Comment by dcbark01** [comment]
For regular torchscript exporting, you need to set the 'memory_efficient' attribute to False prior to exporting. I'm assuming this is the case for mobile as well.

```
from efficientnet_pytorch import EfficientNet
import torch

model = EfficientNet.from_pretrained('efficientnet-b0')
model.set_swish(memory_efficient=False)
scripted_model = torch.jit.script(model)

```

**Comment by TomekPro** [comment]
Hi, unfortunately after adding `model.set_swish(memory_efficient=False)` I get the following error when trying to do `torch.jit.script(model)`:

Tried to access nonexistent attribute or method 'expand_ratio' of type 'Tuple[int, int, int, int, int, bool, List[int], float]'.:
  File "C:\Users\topc\AppData\Local\Continuum\anaconda3\envs\long-island\lib\site-packages\efficientnet_pytorch\model.py", line 76
        # Expansion and Depthwise Convolution
        x = inputs
        if self._block_args.expand_ratio != 1:
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            x = self._swish(self._bn0(self._expand_conv(inputs)))
        x = self._swish(self._bn1(self._depthwise_conv(x)))

It seems to be the same issue as [here](https://github.com/lukemelas/EfficientNet-PyTorch/issues/156). Maybe you have an idea how to fix it?

**Comment by TomekPro** [comment]
Using torch.jit.trace instead of torch.jit.script helped.
