### ISSUE TITLE
How to remove the last layer?

### ISSUE THREAD

**Issue by Zacchaeus14** [lukemelas/EfficientNet-PyTorch#227]
Hi,
Great repo!
I'm doing an image retrieval task. I've already trained the model on my dataset and would like to use the backbone for feature extraction. In other words, I would like the output to be a feature vector. Should I simply remove the last _fc layer?
Thank you in advance!
Best,
Zach

**Comment by lukemelas** [comment]
Like this example from the README? 

```
model = EfficientNet.from_pretrained('efficientnet-b0')
features = model.extract_features(img)
```

**Comment by Zacchaeus14** [comment]
@lukemelas Thank you!

**Comment by Zacchaeus14** [comment]
@lukemelas Hi Lukemelas, I'm still a little confused. For b0, I expect a feature vector with torch.Size([1, 1280]), however I got torch.Size([1, 1280, 7, 7]). For ResNet I hook output of the last average pooling layer. How can I implement this in efficientnet?

**Comment by lukemelas** [comment]
Does this work? 
```python
features = model.extract_features(img)
pooled_features = torch.nn.functional.adaptive_avg_pool2d(features, 1)
```

**Comment by Zacchaeus14** [comment]
@lukemelas Got it! curious if setting model._fc = torch.nn.Identity() would work?

**Comment by lukemelas** [comment]
Yup, that should work too!

**Comment by Zacchaeus14** [comment]
@lukemelas Now I'm clear. Thank you!
