### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by yja1** [lukemelas/EfficientNet-PyTorch#23]
File "test.py", line 11, in <module>
    model = EfficientNet.from_pretrained('efficientnet-b0')
  File "/EfficientNet_pyt/efficientnet_pytorch/model.py", line 188, in from_pretrained
    load_pretrained_weights(model, model_name)
  File "/EfficientNet_pyt/efficientnet_pytorch/utils.py", line 244, in load_pretrained_weights
    model.load_state_dict(state_dict)
  File "/env_pytorch0.4_py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientNet:
        Unexpected key(s) in state_dict: "_bn0.num_batches_tracked", "_blocks.0._bn1.num_batches_tracked", "_blocks.0._bn2.num_batches_tracked", "_blocks.1._bn0.num_batches_tracked", "_blocks.1._bn1.num_batches_tracked", "_blocks.1._bn2.num_batches_tracked", "_blocks.2._bn0.num_batches_tracked", "_blocks.2._bn1.num_batches_tracked", "_blocks.2._bn2.num_batches_tracked", "_blocks.3._bn0.num_batches_tracked", "_blocks.3._bn1.num_batches_tracked", "_blocks.3._bn2.num_batches_tracked", "_blocks.4._bn0.num_batches_tracked", "_blocks.4._bn1.num_batches_tracked", "_blocks.4._bn2.num_batches_tracked", "_blocks.5._bn0.num_batches_tracked", "_blocks.5._bn1.num_batches_tracked", "_blocks.5._bn2.num_batches_tracked", "_blocks.6._bn0.num_batches_tracked", "_blocks.6._bn1.num_batches_tracked", "_blocks.6._bn2.num_batches_tracked", "_blocks.7._bn0.num_batches_tracked", "_blocks.7._bn1.num_batches_tracked", "_blocks.7._bn2.num_batches_tracked", "_blocks.8._bn0.num_batches_tracked", "_blocks.8._bn1.num_batches_tracked", "_blocks.8._bn2.num_batches_tracked", "_blocks.9._bn0.num_batches_tracked", "_blocks.9._bn1.num_batches_tracked", "_blocks.9._bn2.num_batches_tracked", "_blocks.10._bn0.num_batches_tracked", "_blocks.10._bn1.num_batches_tracked", "_blocks.10._bn2.num_batches_tracked", "_blocks.11._bn0.num_batches_tracked", "_blocks.11._bn1.num_batches_tracked", "_blocks.11._bn2.num_batches_tracked", "_blocks.12._bn0.num_batches_tracked", "_blocks.12._bn1.num_batches_tracked", "_blocks.12._bn2.num_batches_tracked", "_blocks.13._bn0.num_batches_tracked", "_blocks.13._bn1.num_batches_tracked", "_blocks.13._bn2.num_batches_tracked", "_blocks.14._bn0.num_batches_tracked", "_blocks.14._bn1.num_batches_tracked", "_blocks.14._bn2.num_batches_tracked", "_blocks.15._bn0.num_batches_tracked", "_blocks.15._bn1.num_batches_tracked", "_blocks.15._bn2.num_batches_tracked", "_bn1.num_batches_tracked".

**Comment by zlheos** [comment]
pytorch version use latest
I use 1.1

**Comment by lukemelas** [comment]
As zlheos mentioned, can you try moving to PyTorch 1.0 or 1.1?

**Comment by yja1** [comment]
I used pytorch 1.0 is OK.
thx~
