### ISSUE TITLE
Pretrained models have terrible performance

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [lukemelas/EfficientNet-PyTorch#237]
I evaluate all the efficient architecture with the pre-trained weights available on this repo and the performances are *different than the ones shared in this repo*.  
What is going on? 

```
|                 |    top1 |    top5 |   time (s) |
|:----------------|--------:|--------:|-----------:|
| efficientnet-b0 | 0.7465  | 0.91932 |    78.2806 |
| efficientnet-b1 | 0.7461  | 0.91616 |   120.922  |
| efficientnet-b2 | 0.79394 | 0.9459  |   159.07   |
| efficientnet-b3 | 0.81212 | 0.95526 |   253.05   |
| efficientnet-b4 | 0.82788 | 0.96234 |   542.88   |
| efficientnet-b5 | 0.8345  | 0.9663  |  1049.4    |
| efficientnet-b6 | 0.84024 | 0.96908 |  1853.14   |
| efficientnet-b7 | 0.84106 | 0.9692  |  3245.83   |
```

Images are resized using the following code

```python
resize_size = {

    'efficientnet-b0': 224,
    'efficientnet-b1': 240,
    'efficientnet-b2': 260,
    'efficientnet-b3': 300,
    'efficientnet-b4': 380,
    'efficientnet-b5': 456,
    'efficientnet-b6': 528,
    'efficientnet-b7': 600,

}

transform = Compose([
            Resize(size, Image.BICUBIC),
            CenterCrop(size),
            ToTensor(),
            Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
   ])

valid_dataset = ImageNet(root='/home/zuppif/Downloads/ImageNet', split='val', transform=transform)


valid_loader = torch.utils.data.DataLoader(valid_dataset, batch_size=batch_size, shuffle=False,
                                                num_workers=12, pin_memory=True)
```

My code to compute (I used `sotabencheval`) top-1 and top-5 is correct.

**Comment by FrancescoSaverioZuppichini** [comment]
[Edit] I did not resize the images

**Comment by daixiangzi** [comment]
I meet same problems

**Comment by FrancescoSaverioZuppichini** [comment]
Welcome to the club :) I guess the author is not interested at all. I am working on my [own library](https://github.com/FrancescoSaverioZuppichini/glasses) with human-readable code.

**Comment by lukemelas** [comment]
Hi, I'm certainly interested. This issue hasn't been active since October, so I assumed it was resolved. What numbers are you getting?

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @lukemelas, I hope you are doing great! The issue hasn't been active since October since I was waiting for an answer from you. 

[Here](https://gist.github.com/FrancescoSaverioZuppichini/5ae3205af1bf76545647f69b54277621) you can find the code used to compute the scores. 

I have run it again **today** and these are the results:

|    |    top1 |    top5 |      time |   batch |
|---:|--------:|--------:|----------:|--------:|
|  0 | 0.7646  | 0.9303  |   89.9862 |     256 |
|  1 | 0.78398 | 0.94164 |  134.929  |     128 |
|  2 | 0.79812 | 0.94644 |  162.524  |      64 |
|  3 | 0.81318 | 0.95456 |  270.139  |      64 |
|  4 | 0.82752 | 0.96224 |  533.406  |      32 |
|  5 | 0.8384  | 0.96748 | 1089.04   |      32 |
|  6 | 0.84134 | 0.9697  | 1860.45   |      32 |
|  7 | 0.84486 | 0.96974 | 3277.51   |      32 |

Now the results are consistent with yours (**even slightly better** in`b0`).  But, interesting, now training is slower than October, I have updated my drivers. Thank you nvidia!

@daixiangzi I hope my benchmark code can help you, sometimes it is a little bit tricky to get the preprocessing part correct, for instance, if the resize function should use bicubic or not.

Just a side note, it is embarrassing how slow these models are. I got it they had to market it by calling `Efficient***` but, really, depth-wise conv? Ugh!

Let me know your thoughts :)

**Comment by daixiangzi** [comment]
> Hi @lukemelas, I hope you are doing great! The issue hasn't been active since October since I was waiting for an answer from you.
> 
> [Here](https://gist.github.com/FrancescoSaverioZuppichini/5ae3205af1bf76545647f69b54277621) you can find the code used to compute the scores.
> 
> I have run it again **today** and these are the results:
> 
> top1	top5	time	batch
> 0	0.7646	0.9303	89.9862	256
> 1	0.78398	0.94164	134.929	128
> 2	0.79812	0.94644	162.524	64
> 3	0.81318	0.95456	270.139	64
> 4	0.82752	0.96224	533.406	32
> 5	0.8384	0.96748	1089.04	32
> 6	0.84134	0.9697	1860.45	32
> 7	0.84486	0.96974	3277.51	32
> Now the results are consistent with yours (**even slightly better** in`b0`).
> 
> @daixiangzi I hope my benchmark code can help you, sometimes it is a little bit tricky to get the preprocessing part correct, for instance, if the resize function should use bicubic or not.
> 
> Just a side note, it is embarrassing how slow these models are. I got it they had to market it by calling `Efficient***` but, really, depth-wise conv? Ugh!
> 
> Let me know your thoughts :)

thank you , when I use resnet18 pre_model in imagine,my task acc is 92%(binary classification),but I use efficient_B0,acc only is 82%,input image size is 224*224,

**Comment by lukemelas** [comment]
Awesome, I'm glad to see that the results are now consistent.

I also totally agree about the depthwise conv! It's faster with `fp16`, but even there it could be faster. Hoping to see custom cuda code that speeds it up in pytorch soon.

Also, your glasses library looks very cool :)

**Comment by FrancescoSaverioZuppichini** [comment]
@daixiangzi are you using pre-trained weights? As far as I know, they used lots of tricks to train the efficientnet models.
@lukemelas I am also very happy to have the same results, I am wondering what was wrong in the first place. Have you had a look at [RegNet](https://arxiv.org/abs/2003.13678), they look like a good alternative. Thank you for the nice feedback, If you want to help out just let me know 😄 

I think we can close the issue, @lukemelas do you want to do the honors?

**Comment by daixiangzi** [comment]
Yes,resnet18 use imagenet weights,efficient use this rep offer











我没有什么天赋，我只是生而由来的执着。

---Original---

**Comment by FrancescoSaverioZuppichini** [comment]
It may be that resnet18 is better for your task, you have to consider that this is rocket science, sota models are sota only for one specific task

**Comment by daixiangzi** [comment]
Haha，maybe











我没有什么天赋，我只是生而由来的执着。

---Original---

**Comment by lukemelas** [comment]
:)
