### ISSUE TITLE
Example: Feature Extraction

### ISSUE THREAD

**Issue by peterhsu2018** [lukemelas/EfficientNet-PyTorch#24]
Hi, if i try this 
`features = model.extract_features(imgs)`
Can i show image by open-cv?

**Comment by lukemelas** [comment]
Hello, what exactly do you mean? Do you want to show the image in OpenCV? 

The features are simple high-dimensional vectors, so you can't really "show" them as images. There's CAM/GradCAM/etc., but that's a whole different thing.

**Comment by lukemelas** [comment]
Keeping this open for now in case you have more questions, but I'll close it soon if not.

**Comment by peterhsu2018** [comment]
@lukemelas Yes, that's my point,
so if i want to show the images from the feature map, i should try the grad cam? Do you have any good example to do that? Thanks!

**Comment by lukemelas** [comment]
Yes, if you want to overlay heatmaps on top of images, GradCAM is the way to go. Here's a solid implementation: https://github.com/kazuto1011/grad-cam-pytorch

**Comment by MyLtYkRiTiK** [comment]
Hello! @lukemelas, can you provide, please, code for GradCAM? 
I tried to use code you point, but I have very unrealistic visualizations with huge attention in one place, nearly identical for every image.
And I do not understand what the problem.
