### ISSUE TITLE
what if use efficient net-b0 to extract large image features

### ISSUE THREAD

**Issue by mzy97** [lukemelas/EfficientNet-PyTorch#240]
Hi, thank you for sharing this great repo.

I want to use efficientnet-b0 (for small # param and better behavior than resnet18) as backbone to extract RGB features, the optimal input image size is 224x224, but in my application, i want to input a 250x1300 (high resolution) image. Will the feature extraction ability drop alot when i input large image to efficientnet-b0?

**Comment by zwd973** [comment]
yes, the resolution should match the arch, or the ability will drop a lot.

**Comment by lukemelas** [comment]
Closing this issue, thanks to zwd973 for responding a long time ago
