### ISSUE TITLE
Installation failed on Nvidia Jetson

### ISSUE THREAD

**Issue by kochsebastian** [lukemelas/EfficientNet-PyTorch#243]
I want to use your EfficentNet implementation on a Jetson Xavier.
But when trying to install it via pip or from source I get the following error:
```

Collecting efficientnet_pytorch
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/4e/83/f9c5f44060f996279e474185ebcbd8dbd91179593bffb9abe3afa55d085b/efficientnet_pytorch-0.7.0.tar.gz
Collecting torch (from efficientnet_pytorch)
  Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/torch.egg-info
    writing pip-egg-info/torch.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/torch.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/torch.egg-info/requires.txt
    writing top-level names to pip-egg-info/torch.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/torch.egg-info/SOURCES.txt'
    error: package directory 'torch/cuda' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rebwbqxa/torch/

```
I tried to update the setuptools package, no change.

It seems to be a PyTorch (Version 1.6) issue.
PyTorch is not installed from the original source on the Jetson devices, but you have to follow these instructions:
https://elinux.org/Jetson_Zoo

Any help would be appreciated.

**Comment by pieterbl86** [comment]
> I want to use your EfficentNet implementation on a Jetson Xavier.
> But when trying to install it via pip or from source I get the following error:
> 
> ```
> 
> Collecting efficientnet_pytorch
>   Cache entry deserialization failed, entry ignored
>   Using cached https://files.pythonhosted.org/packages/4e/83/f9c5f44060f996279e474185ebcbd8dbd91179593bffb9abe3afa55d085b/efficientnet_pytorch-0.7.0.tar.gz
> Collecting torch (from efficientnet_pytorch)
>   Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
>     Complete output from command python setup.py egg_info:
>     running egg_info
>     creating pip-egg-info/torch.egg-info
>     writing pip-egg-info/torch.egg-info/PKG-INFO
>     writing dependency_links to pip-egg-info/torch.egg-info/dependency_links.txt
>     writing requirements to pip-egg-info/torch.egg-info/requires.txt
>     writing top-level names to pip-egg-info/torch.egg-info/top_level.txt
>     writing manifest file 'pip-egg-info/torch.egg-info/SOURCES.txt'
>     error: package directory 'torch/cuda' does not exist
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rebwbqxa/torch/
> ```
> 
> I tried to update the setuptools package, no change.
> 
> It seems to be a PyTorch (Version 1.6) issue.
> PyTorch is not installed from the original source on the Jetson devices, but you have to follow these instructions:
> https://elinux.org/Jetson_Zoo
> 
> Any help would be appreciated.

@kochsebastian sorry to bother you Sebastian. Were you able to solve this issue? Or do you alternatively use the ONNX export/import?

**Comment by maxmaier59** [comment]
"The problem is that "setup.py" in the fairseq directory specifies "torch" in the "install_requires" section

 install_requires=[
            "cffi",
            "cython",
            'dataclasses; python_version<"3.7"',
            "hydra-core<1.1",
            "omegaconf<2.1",
            'numpy<1.20.0; python_version<"3.7"',
            'numpy; python_version>="3.7"',
            "regex",
            "sacrebleu>=1.4.12",
            "torch",
            "tqdm",
            
            
This causes the "pip3 install --editable ./" command to download "torch-0.1.2.post2.tar.gz" from the pythonhosted  packages. This package does not include cuda:

![image](https://user-images.githubusercontent.com/80212528/112549264-cc3fca00-8dbd-11eb-9cc5-43b8996547e9.png)

The solution for me was to delete the line "torch" in "setup.py"

In addition you need to follow the descriptions at https://elinux.org/Jetson_Zoo to install PyTorch
This one includes Cuda
