### ISSUE TITLE
How to use the saved model in a closed system with no internet access.

### ISSUE THREAD

**Issue by Rishav09** [lukemelas/EfficientNet-PyTorch#252]
Hi,
I am using a cluster in which I have to submit jobs, it is a kind of a closed system, so it doesn't have internet access.
I have cloned the directory in the same folder as my training script so that it could load the models from there but even then I am getting 
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)
`
This error comes up when the training script is trying to access something on internet.
Are there any suggestions which I can do to resolve this problem, like forcing my script to first check the directories available before pinging the internet for downloading.

**Comment by lukemelas** [comment]
You have an issue loading the pretrained model? You can download the weights manually (links in the utils file) and then load using .load_state_dict.
