### ISSUE TITLE
the use of efficientnet-b0

### ISSUE THREAD

**Issue by Hello526** [lukemelas/EfficientNet-PyTorch#26]
Hi.
Is the EfficientNet-B0 only for image classification, not for object detection?

**Comment by Hello526** [comment]
The output of the EfficientNet-B0 has only the classification, but no location information.

**Comment by tbmreza** [comment]
> Hi.
> Is the EfficientNet-B0 only for image classification, not for object detection?

Yes. And it's not that it hasn't been implemented, the concepts of classification and detection algorithm are different. Look up 'object detection'.

This picture helps me whenever my mental needs sanity check re classification/detection.
![image](https://user-images.githubusercontent.com/17718201/59441039-227a8d80-8e22-11e9-8963-3c633033ad6c.png)

**Comment by lukemelas** [comment]
Yes, as tbmreza said, EfficientNet is for image classification. 

That being said, image classification networks form the backbone of a number of object networks. Once we get training working reliably, we'll be able to train object detection networks with EfficientNets as their backbone.
