### ISSUE TITLE
How to load a custom model

### ISSUE THREAD

**Issue by thanhsang298** [lukemelas/EfficientNet-PyTorch#270]
Hi, thank for great repo, I wanna ask you how to load a custom EfficientNet model using Pytorch? :D

**Comment by lukemelas** [comment]
You can load using `.from_pretrained ` or with `.load_state_dict` as in usual PyTorch code.

Here's a Colab: https://colab.research.google.com/drive/1JLisFMRI8rxm5TUvbcUmZBmAKUcohyvF?usp=sharing

I'm going to close this issue, feel free to re-open it if you have any questions.
