### ISSUE TITLE
Change downsample ratio to 16

### ISSUE THREAD

**Issue by gauravfotedar** [lukemelas/EfficientNet-PyTorch#276]
Currently, downsampling is 32. Is there a way to change it to 16 and still use pre-trained weights?

EDIT: I ended up reducing stride in the block_args. Is this the best way? Is there a way to know the stride of which block (early or late stage) should be changed for minimal change in performance?

**Comment by lukemelas** [comment]
Yes, that should be a good way. Regardless, if it is possible, you will want to finetune the network before you use it, because it has been trained with 32x downsampling. That being said, since you only did a tiny change, it should be very quick to finetune it.

**Comment by lukemelas** [comment]
Going to close this, just reopen it if you have more questions
