### ISSUE TITLE
A Doubt on segmentation

### ISSUE THREAD

**Issue by Rituraj-commits** [lukemelas/EfficientNet-PyTorch#288]
I want to use the feature extractor for image segmentation. But how can I pass grayscale images to the model? When I use channel 1 it gives an error. Any suggestions?

![error_3](https://user-images.githubusercontent.com/64738909/118707625-60676400-b838-11eb-8d2e-1a84cc0ad8c4.png)

**Comment by lukemelas** [comment]
How did you construct the model?

**Comment by Rituraj-commits** [comment]
I found the fix after looking through the docs

**Comment by AdriannaGmz** [comment]
Hi! @Rituraj-commits  could you share how you accomplished to feed the network with grayscale images?
I'm trying to achieve the same, but since it expects for rgb, I have to convert them.. but I bet there should be a smarter way :)
