### ISSUE TITLE
Cannnot training due to Expected CUDA but got CPU instead

### ISSUE THREAD

**Issue by thinhnggia** [lukemelas/EfficientNet-PyTorch#29]
Yesterday before the update of B4 band B5, I can still train the model from scratch, however, after the update, I see that it seems that the drop_connect function in the utils is not set to CUDA as I think, so it would conflict with the input data which is loaded to GPU already

**Comment by lukemelas** [comment]
Yes, this makes sense. I'll fix it tomorrow.

**Comment by changwuxie** [comment]
@thinhnggia 
you can advise the fuction 'drop_connect' in utils.py  
change: random_tensor += torch.rand([batch_size, 1, 1, 1], dtype=inputs.dtype)
to        : random_tensor += torch.rand([batch_size, 1, 1, 1], dtype=inputs.dtype,device=inputs.device)
Then it works!

**Comment by lukemelas** [comment]
Thanks, @changwuxie ! Just fixed it.
