### ISSUE TITLE
Transfer learning on pretrained models

### ISSUE THREAD

**Issue by chinembedded** [lukemelas/EfficientNet-PyTorch#326]
Hi, 

Thanks for the repo. Great work!

Could you please share if there are any ways to finetune these models on custom datasets? I want to retrain the pretrained networks on custom datasets.

**Comment by chinembedded** [comment]
Got it resolved but, it would be good if you share your solution as well.

**Comment by luisjdtt** [comment]
Hi! Could you explain or share the way you did it? I'm trying to do the same thing. I want to fine-tune the pretrained model on a a limited custom dataset.
