### ISSUE TITLE
Problem with pretrained b5

### ISSUE THREAD

**Issue by ChipsSpectre** [lukemelas/EfficientNet-PyTorch#33]
Hey,

when trying to use GPU with the pretrained b5, the *binary_tensor* in this method remains a normal float tensor and this lets the program crash (line 73).

![image](https://user-images.githubusercontent.com/11499442/59926479-a80dc700-943a-11e9-8f89-3d4acb4f07e7.png)

Would it be ok to create a pull request in order to move it to a device / support CUDA gpus?

**Comment by lartpang** [comment]
https://github.com/lukemelas/EfficientNet-PyTorch/issues/29
