### ISSUE TITLE
Inference speed between the self trained model and the model provided by model_zoo

### ISSUE THREAD

**Issue by liuqk3** [lukemelas/EfficientNet-PyTorch#39]
@lukemelas  Hi, Luke,

Thanks for your great work! I have written a training script to train my own model EfficientNet-B0 (based on the pre-trained model on ImageNet). The only modification to the model is that I changed the last fc layer (i.e. the number of classes). And then I tested the inference time using the self trained model, the results are:
```
CPU time cost: 0.772s
GPU time cost: 0.021s
```
And you can see that the model is so slow on CPU. Then I tested the  inference time with `/examples/simple/example.ipynb` you provided, the results are:
```
CPU time cost: 0.162s
```
Do you know why there is a big gap between the time cost on CPU of these two models?

Thanks a lot !

**Comment by lukemelas** [comment]
Hi @liuqk3,

I'm not sure what could be causing the difference in inference times. Have you managed to resolve the issue?

**Comment by liuqk3** [comment]
@lukemelas Yes, I have solved this issue.
It is becasue there are too many denomal digits (the digits whose magnitude is less than 1e-32) in myself trained model, and the computation of denormal digits in CPU is much expensive than normal digits. See [this](https://github.com/pytorch/pytorch/issues/19651)  and [this](https://stackoverflow.com/questions/36781881/why-denormalized-floats-are-so-much-slower-than-other-floats-from-hardware-arch) for more info. about this phenomena. 

I statistics on myself trained and ImageNet pretained models are as follows:

```
                    self trained    ImageNet pretrained
number of denormal:  0                   0
number of denormal:  169                 0
number of denormal:  0                   0
number of denormal:  1920                0
number of denormal:  401                 0
number of denormal:  28960               0
number of denormal:  31760               0
number of denormal:  16640               0
number of denormal:  68873               0
number of denormal:  71236               0
number of denormal:  53321               0
number of denormal:  214271              0
number of denormal:  215808              0
number of denormal:  218688              0
number of denormal:  188933              0
```

After the model para. is loaded, I set denomal digits to 0. The inference time can be optimized ```0.772s-->0.160s```.

The PyTorch has also provided a function to avoid denormal digits ```torch.set_flush_denormal(True)```, then the inference time is optimized to ```0.160s-->0.111s```.

**Comment by lukemelas** [comment]
Great to hear you solved the issue! Interesting, I didn't know that about the denormal digits thing, thanks for linking those threads. 

I'm closing this issue as you've solved it.
