### ISSUE TITLE
why the params size of b0 model is 20M rather than 5.3M

### ISSUE THREAD

**Issue by lightfate** [lukemelas/EfficientNet-PyTorch#40]
Hi, @lukemelas ~
I'm so excited about your code.
I have a question.  You said that the Params size of the b0 model is 5.3M，but the size of pretrained model what you offered is 20.3M,  
and then I test it through torchsummary, which shows that Params size (MB): 20.17, why?
**************************************************
#torchsummary code:
from efficientnet_pytorch import EfficientNet
modelBody= EfficientNet.from_pretrained('efficientnet-b2').to(device)
from torchsummary import summary
summary(modelBody, input_size=(3, 224, 224))

***************************************************************
#result
Total params: 5,288,548
Trainable params: 5,288,548
Non-trainable params: 0
Input size (MB): 0.57
Forward/backward pass size (MB): 107.31
Params size (MB): 20.17
Estimated Total Size (MB): 128.06
**************************************************

**Comment by lukemelas** [comment]
5.3M refers to the number of parameters, whereas 20 refers to the size of the params in megabytes. It makes sense that it's around 4 times the number of params.

**Comment by lukemelas** [comment]
Closing this.

**Comment by EtheneXiang** [comment]
> torchsummary

one para's type is float32 = 4 * int8 = 32bit
so 5,288,548 * 4  = 20.17MB
that's all
