### ISSUE TITLE
Code from pip: expected backend CUDA and dtype Float but got backend CPU and dtype Float.

### ISSUE THREAD

**Issue by Jianfei2333** [lukemelas/EfficientNet-PyTorch#43]
Greetings! I've got the bug "expected backend CUDA and dtype Float but got backend CPU and dtype Float". This bug was fixed in #29, but the package from pip was not upgraded. Are you planning to fix it recently or to fix it with next upgrade?

**Comment by lukemelas** [comment]
Yes, it will be fixed in pip soon.

**Comment by lukemelas** [comment]
This is now fixed in pip!
