### ISSUE TITLE
How to train efficientnet from b0 to b1

### ISSUE THREAD

**Issue by dsim174** [lukemelas/EfficientNet-PyTorch#45]
Hi! 

I'm trying to understand efficientnet code, but I don't know how to train the network from b0 to b1 under the same dataset.

Does it fine-tune b1 from the pretrained b0 or just re-train?

Thanks!

**Comment by lukemelas** [comment]
Hello, 

B1 is an entirely different architecture from B0. As a result, it has to be trained separately from scratch. You can't really go from B0 to B1. 

Best,
Luke
