### ISSUE TITLE
How to extract an intermediate feature from efficientnet?

### ISSUE THREAD

**Issue by Soo95** [lukemelas/EfficientNet-PyTorch#51]
Hi, I'm making U-Net encoded by efficient-b4.
I tried extracting feature as I did in resnet, but it doesn't work with 'NotImplementedError'

`backbone = EfficientNet.from_pretrained('efficientnet-b4')`
`nn.Sequential(*list(backbone.children())[:3])(torch.rand(2,3,512,512))`

Error>

> ---------------------------------------------------------------------------
> NotImplementedError                       Traceback (most recent call last)
> <ipython-input-130-7602963f62fc> in <module>
> ----> 1 nn.Sequential(*list(backbone.children())[:3])(inp)
> 
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     491             result = self._slow_forward(*input, **kwargs)
>     492         else:
> --> 493             result = self.forward(*input, **kwargs)
>     494         for hook in self._forward_hooks.values():
>     495             hook_result = hook(self, input, result)
> 
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py in forward(self, input)
>      90     def forward(self, input):
>      91         for module in self._modules.values():
> ---> 92             input = module(input)
>      93         return input
>      94 
> 
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     491             result = self._slow_forward(*input, **kwargs)
>     492         else:
> --> 493             result = self.forward(*input, **kwargs)
>     494         for hook in self._forward_hooks.values():
>     495             hook_result = hook(self, input, result)
> 
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in forward(self, *input)
>      86             registered hooks while the latter silently ignores them.
>      87         """
> ---> 88         raise NotImplementedError
>      89 
>      90     def register_buffer(self, name, tensor):
> 
> NotImplementedError: 

There is a way to extract the final feature by 'extract_features' function, however I want to get an intermediate feature for skip connection.
Is there any method to extract it?

**Comment by Soo95** [comment]
Hi, I found the solution that a hook callbacks can do that!
I close this issue

**Comment by vakkov** [comment]
Can you, please, elaborate on the solution? It would be appreciated

**Comment by wjensheng** [comment]
I also also having the same error, can you please explain how you resolve it, @Soo95. Thank you.

**Comment by tienthegainz** [comment]
Look forward to your answer too @Soo95

**Comment by Soo95** [comment]
Hi, I just notice many of you wonder how to do this.
It'd be good to see this nice open repository (https://github.com/zhoudaxia233/EfficientUnet-PyTorch) which implemented it by hook callback.
