### ISSUE TITLE
Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by LitvinchukAndrey** [lukemelas/EfficientNet-PyTorch#52]
Hi there! Thanks for your great repo, but i faced with some difficulties while trying to inference on device ('cuda:0'). My code: 
`device = torch.device('cuda:0')`
`tfms = transforms.Compose([transforms.Resize(224), transforms.ToTensor(), transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),])`
`img = tfms(Image.open('img.png')).unsqueeze(0)`
`img.to(device)`
`model.to(device)`
`model.eval()`
`with torch.no_grad():
    outputs = model(img)`
And thrown error: 
`RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same`

**Comment by cardoso-neto** [comment]
I'm pretty sure `Tensor.to(device)` is not an in-place operation and you're discarding the cuda tensor using it as such.

**Comment by LitvinchukAndrey** [comment]
So it's impossibile to run on GPU or i missed something?

**Comment by cardoso-neto** [comment]
Are you serious?
Your tensor's the problem.

Did you even try `img = img.to(device)` as I've told you?

**Comment by LitvinchukAndrey** [comment]
Sorry, i didn't understand your answer. Thank you very much,,

**Comment by HoiM** [comment]
The problem is that you didn't convert the type of the input data correctly. You can try something like this:
`
batch = torch.from_numpy(image_batch).type(torch.cuda.FloatTensor)
batch_features = model.extract_features(batch)
`

**Comment by P-DX** [comment]
hi, do you solve this problem?
could you share the solution with me?

**Comment by litvinich** [comment]
I just wrote
```
img = img.to(device)
```
As wrote before, sending tensor to device is not inplace operation and it returns new tensor.

**Comment by P-DX** [comment]
> I just wrote
> 
> ```
> img = img.to(device)
> ```
> 
> As wrote before, sending tensor to device is not inplace operation and it returns new tensor.

Thanks a lot!
Maybe i wrote this:

    batch_data=[b.to(device=device) for b in batch_data]

causes something wrong.
Thank you!!
