### ISSUE TITLE
Error when get intermediate output

### ISSUE THREAD

**Issue by beantr96** [lukemelas/EfficientNet-PyTorch#53]
Hello,
I'm trying to get intermediate output from Pytorch like this:
```python 
model = EfficientNet.from_pretrained('efficientnet-b0')
features = nn.Sequential(*list(model.children())[:-1])
x = torch.rand((4,3,224,224))
y = features(x)
```
And Colab throws me the error

 ---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-26-17722b8cd4a4> in <module>()
      2 features = nn.Sequential(*list(model.children())[:-1])
      3 x = torch.rand((4,3,224,224))
----> 4 y = features(x)

3 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py in forward(self, input)
     90     def forward(self, input):
     91         for module in self._modules.values():
---> 92             input = module(input)
     93         return input
     94 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in forward(self, *input)
     86             registered hooks while the latter silently ignores them.
     87         """
---> 88         raise NotImplementedError
     89 
     90     def register_buffer(self, name, tensor):

NotImplementedError:

**Comment by ShiroKL** [comment]
Hi,

I got the same error, did you manage to fix that ?

**Comment by chinglamchoi** [comment]
Same error here, any solution?

**Comment by lukemelas** [comment]
Use `.extract_features()`, as in the README:

```
from efficientnet_pytorch import EfficientNet
model = EfficientNet.from_pretrained('efficientnet-b0')

# ... image preprocessing as in the classification example ...
print(img.shape) # torch.Size([1, 3, 224, 224])

features = model.extract_features(img)
print(features.shape) # torch.Size([1, 1280, 7, 7])
```

**Comment by chinglamchoi** [comment]
Thanks, this works well. However, is there any way to extract the intermediate feature maps? Thanks!

**Comment by JonathanSum** [comment]
@lukemelas 
I think we should be allowed to access the model layer by indexing to apply hook to access the  intermediate layers rather than a .extract_features()
