### ISSUE TITLE
trans to pb ,but pb run very very slow

### ISSUE THREAD

**Issue by beyondli** [lukemelas/EfficientNet-PyTorch#61]
I trans this efficientnet pth to pb,and test it ,this pb model can run correctly, but it inference time is 10X slow than pth model, seems pth->onnx->pb some thing wrong ,I checked maybe depth wise in pb  is not totally run in GPU? anyone can run in pb as fast as in pth? thanks!

env:
pytorch:1.0
TF:1.10
onnx-tf:1.2.1
onnx:1.5

**Comment by gaoruiyang** [comment]
same question!
more than 10x slower
env:
pytorch 1.4.0+cu100
tf 1.15.4
onnx 1.6.0
onnx-tf 1.3.0
