### ISSUE TITLE
Hi,does the EfficientNet have activate function like relu?

### ISSUE THREAD

**Issue by zxyyxzz** [lukemelas/EfficientNet-PyTorch#62]
Hi:
   Thanks for your excellent implement, it is really benificial for us.
   But i did not find the activate function in this code.
   Hope you can help me:-)
Best
Xinyu

**Comment by lukemelas** [comment]
It's here:

https://github.com/lukemelas/EfficientNet-PyTorch/blob/master/efficientnet_pytorch/utils.py#L39

Hope this helps!

**Comment by zxyyxzz** [comment]
> It's here:
> 
> https://github.com/lukemelas/EfficientNet-PyTorch/blob/master/efficientnet_pytorch/utils.py#L39
> 
> Hope this helps!

Thanks love you!
