### ISSUE TITLE
6 channel input image

### ISSUE THREAD

**Issue by DecentMakeover** [lukemelas/EfficientNet-PyTorch#67]
Hi 

Thanks for sharing your work, how could i modify efficientNet  to take in input as a 6 channel image.

Thanks in advance.

**Comment by saurabh-kataria** [comment]
Easy. Change line 123 in model.py from `n_channels = 3` to `n_channels = 6`.

**Comment by DecentMakeover** [comment]
Hey , this does not seem to work 

  File "/media/bubbles/fecf5b15-5a64-477b-8192-f8508a986ffe/ai/ryan/odir/EfficientNet-PyTorch/efficientnet_pytorch/utils.py", line 126, in forward
    x = F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[11, 6, 225, 225] to have 3 channels, but got 6 channels instead

Any suggestions on this?

**Comment by shijianjian** [comment]
Hi @DecentMakeover,

I did some experiments on b3, the following code worked for me, just to duplicate the weight as well as the input channels:
```
model._conv_stem.in_channels = 6
model._conv_stem.weight = torch.nn.Parameter(torch.cat([model._conv_stem.weight, model._conv_stem.weight], axis=1))
```
