### ISSUE TITLE
drop_connect_rate not use?

### ISSUE THREAD

**Issue by nvlong21** [lukemelas/EfficientNet-PyTorch#7]
https://github.com/lukemelas/EfficientNet-PyTorch/blob/6d36a35dfdcb65a7915472286486e1b8f750e5b6/efficientnet_pytorch/model.py#L161
I think: x = block(x, drop_connect_rate = drop_connect_rate).

**Comment by lukemelas** [comment]
I left out drop connect because drop connect was not used in the original TensorFlow implementation (as per the link in the comment on that line). It seems this was a mistake, but I will wait for the original issue (#381 on the original repo) to be resolved in order to edit this line.

**Comment by szymonmaszke** [comment]
It got fixed in [#381](https://github.com/tensorflow/tpu/issues/381) and it seems they use `drop_connect_rate` with `0.21.

**Comment by lukemelas** [comment]
Yup! This will be fixed in the next version of the repo.
