### ISSUE TITLE
Reproduce the accuracy in  EfficientNet-paper

### ISSUE THREAD

**Issue by zhjpqq** [lukemelas/EfficientNet-PyTorch#81]
Here is a reproduce by the lr-scheduler and data-augmentation of ResNet-style

| model  | Input | Layers  | Params  | FLOPs  | Stages  |  Top1-Accuracy  | GPU-time |
| ------- | ------- | ------- | ------- | ------- | ------- | ------ | ------- |
| EfficientNet-B0  | 224  | 82   | 5.29M  | 0.39G  |  5 | 68.69%  |    0.01082s  |
| ScaleNet-vo69    | 224  | 103  | 5.08M  | 4.77G  | **1**  |  71.34% | 0.01567s   |
| ResNet-50        | 224  | 54   | 25.56M  | 4.11G  | 4  | 76.36%  |  0.00778s  |
| ScaleNet-vo21    | 224  | 54   | 25.02M  | 4.64G  | 4  | 74.62%  |  0.00799s     |

The above result of ResNet50 (23.64%)  equals to  the baseline result (23.7%) in FastAuoAugment (https://github.com/kakaobrain/fast-autoaugment)

But with the same training scheduler and data-augmentation, the EfficientB0 is too low ....

Dose anyone have  reproduce the accuracy in  EfficientNet-paper?  I'm now running it with FastAutoAugment, but it still looks bad. So searching for the original training method in pytorch, 3q~

The validation curves can be found here:  http://studyai.com/article/ef115e40

**Comment by BarakBat** [comment]
Any luck with the training? can you share the code?
