### ISSUE TITLE
problem in installing

### ISSUE THREAD

**Issue by FriedrichWilhelmNietzsche** [lukemelas/EfficientNet-PyTorch#9]
![image](https://user-images.githubusercontent.com/30073072/58845459-ce4b0d00-86ad-11e9-9e28-842109b65b8a.png)
![Uploading image.png…]()

**Comment by nizhib** [comment]
Install the latest version from pytorch.org first. You are using the cached one of several years old.

**Comment by lukemelas** [comment]
I am going to close this issue, as it's about PyTorch versioning rather than EfficientNet.
