### ISSUE TITLE
'bool' object has no attribute 'size'.

### ISSUE THREAD

**Issue by PhantomOfLight** [lukemelas/EfficientNet-PyTorch#95]
![image](https://user-images.githubusercontent.com/53218277/67160707-49ab1380-f35c-11e9-8c7b-c403f4348dc1.png)

**Comment by PhantomOfLight** [comment]
This bug exicted with work fast ai

**Comment by warner-benjamin** [comment]
EfficientNet-PyTorch works with fastai. This is not a bug with the library.

From your screenshot I suspect you are using the `cnn_learner` function instead of the `Learner` function to create your model. You should check out the [fastai forums](https://forums.fast.ai/) for more details.

**Comment by PhantomOfLight** [comment]
Thanks your, for answer. It's helped me.
