### ISSUE TITLE
Custom Training using pretrained weights

### ISSUE THREAD

**Issue by suman-19** [lukemelas/EfficientNet-PyTorch#99]
Thanks for releasing EfficientNet Models.

Kindly provide some scripts so that we can do custom training on our own data using your pretrained weights.

Thanks.

**Comment by dexception** [comment]
+1

**Comment by ashuezy** [comment]
+1

**Comment by deimsdeutsch** [comment]
+1

**Comment by llwowowowoll** [comment]
+1

**Comment by nizhib** [comment]
There is https://github.com/pytorch/examples/blob/master/imagenet/main.py for training and fine-tuning pytorch models, just replace torchvision models with efficientnets.

Avoid +1-spamming in comments, there are reactions for that.

**Comment by Michael-Jing** [comment]
It seems that all the pretrained weights can not be downloaded at this time (12th Feb 2020)
